version: '3.8'

services:
  blog-aggregator:
    build: blog-aggregator
    image: oba/blog-aggregator
    deploy:
      resources:
        limits:
          memory: 350m
    ports:
      - "8080:80"
  post-service:
    build: post-service
    image: oba/post-service
    deploy:
      resources:
        limits:
          memory: 350m
    ports:
      - "8081:80"
  user-service:
    build: user-service
    image: oba/user-service
    deploy:
      resources:
        limits:
          memory: 350m
    ports:
      - "8082:80"
  rank-service:
    build: rank-service
    image: oba/rank-service
    deploy:
      resources:
        limits:
          memory: 350m
    ports:
      - "8083:80"
