version: '3.8'

services:
  blog-aggregator:
    build: blog-aggregator
    image: oba/blog-aggregator
    deploy:
      resources:
        limits:
          memory: 350m
    ports:
      - "8080:8080"
