version: '3.8'

services:
  blog-aggregator:
    build: blog-aggregator
    image: oba/blog-aggregator
    env_file:
      - $PWD/kubernetes/services/base/deployments/config-repo/application.env
      - $PWD/kubernetes/services/base/deployments/config-repo/auth-secret.env
    environment:
      - SPRING_CONFIG_LOCATION=file:/config-repo/blog-aggregator.yml
    volumes:
      - $PWD/kubernetes/services/base/deployments/config-repo:/config-repo
    deploy:
      resources:
        limits:
          memory: 350m
    ports:
      - "8080:80"
  post-service:
    build: post-service
    image: oba/post-service
    deploy:
      resources:
        limits:
          memory: 350m
    ports:
      - "8081:80"
  user-service:
    build: user-service
    image: oba/user-service
    deploy:
      resources:
        limits:
          memory: 350m
    ports:
      - "8082:80"
  rank-service:
    build: rank-service
    image: oba/rank-service
    env_file:
      - $PWD/kubernetes/services/base/deployments/config-repo/application.env
      - $PWD/kubernetes/services/base/deployments/config-repo/rank-service.env
    deploy:
      resources:
        limits:
          memory: 350m
    ports:
      - "8083:80"
