apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-aggregator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog-aggregator
  template:
    metadata:
      labels:
        app: blog-aggregator
        version: latest
    spec:
      containers:
        - name: blog-aggregator
          image: oba/blog-aggregator
          imagePullPolicy: Never
          # TODO: env, envFrom
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: 350Mi
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /actuator
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 20
            successThreshold: 1
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
            successThreshold: 1
          # TODO: volumeMounts(config)
        # TODO: volumes(config)
