apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-aggregator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog-aggregator
  template:
    metadata:
      labels:
        app: blog-aggregator
        version: latest
    spec:
      containers:
        - name: blog-aggregator
          image: oba/blog-aggregator
          imagePullPolicy: Never
          env:
            - name: SPRING_CONFIG_LOCATION
              value: file:/config-repo/blog-aggregator.yml
          envFrom:
            - configMapRef:
                name: blog-aggregator-configmap
            - secretRef:
                name: blog-aggregator-secrets
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: 350Mi
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /actuator
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 20
            successThreshold: 1
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: /actuator/health
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
            successThreshold: 1
          volumeMounts:
            - mountPath: /config-repo
              name: config-repo-volume
      volumes:
        - name: config-repo-volume
          configMap:
            name: blog-aggregator-configmap
